---
# Configure XDebug extension

- name: prepare Ansible compatible configuration file for XDebug extension - CentOS
  shell: grep -q -F '[XDebug]' /etc/php.d/xdebug.ini || sed -i '1s/^/[XDebug]\n/' /etc/php.d/xdebug.ini
  changed_when: false
  when: ansible_distribution == "CentOS"

- name: prepare Ansible compatible configuration file for XDebug extension - Ubuntu
  shell: grep -q -F '[XDebug]' /etc/php5/mods-available/xdebug.ini || sed -i '1s/^/[XDebug]\n/' /etc/php5/mods-available/xdebug.ini
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: configure PHP XDebug extension configuration file - CentOS
  ini_file:
       dest=/etc/php.d/xdebug.ini
    section='{{ item.0.section }}'
     option='{{ item.1.option }}'
      value='{{ item.1.value }}'
  with_subelements:
    - php5_ext_xdebug_options
    - options
  when: ansible_distribution == "CentOS"

- name: configure PHP XDebug extension configuration file - Ubuntu
  ini_file:
       dest=/etc/php5/mods-available/xdebug.ini
    section='{{ item.0.section }}'
     option='{{ item.1.option }}'
      value='{{ item.1.value }}'
  with_subelements:
    - php5_ext_xdebug_options
    - options
  when: ansible_distribution == "Ubuntu"
