---
# Install Zend OpCache extension

# If using non-system sources (preferred)

- name: install OpCache extension from non-system sources - CentOS
  yum:
             pkg={{ item }}
    update_cache=yes
           state=present
  with_items:
    - php56w-opcache
  when: ansible_distribution == "CentOS" and
    (BARC_use_non_system_package_sources == true or BARC_use_non_system_package_sources == 'True')

# If using system-sources only

- include: setup-epel-repository.yml
  when: ansible_distribution == "CentOS" and
    (BARC_use_non_system_package_sources == false or BARC_use_non_system_package_sources == 'False')

- name: install OpCache extension from non-system sources - CentOS
  yum:
             pkg={{ item }}
    update_cache=yes
           state=present
  with_items:
    - php-pecl-zendopcache
  when: ansible_distribution == "CentOS" and
    (BARC_use_non_system_package_sources == false or BARC_use_non_system_package_sources == 'Faslse')

# The OpCache extension is already enabled on Ubuntu when using non-system package sources

# The OpCache extension is already enabled on Ubuntu when using system only package sources
